const todos = [{
	id: 1,
	title: 'Shop',
	isDone: false,
	category: 2,
	isUrgent: false,
	description: 'To buy eggs',
	creationDate: new Date(2022, 0, 10, 9, 3, 45),
},
{
	id: 2,
	title: 'Wash clothes',
	isDone: false,
	category: 1,
	isUrgent: false,
	description: 'White clothes',
	creationDate: new Date(2022, 0, 11, 9, 4, 28),
},
{
	id: 3,
	title: 'Wash the dishes',
	isDone: true,
	category: 1,
	isUrgent: true,
	description: 'With soap',
	creationDate: new Date(2022, 0, 12, 9, 12, 7),
},
{
	id: 4,
	title: 'Visit a doctor',
	isDone: false,
	category: 5,
	isUrgent: false,
	description: '12.24.2021',
	creationDate: new Date(2022, 0, 10, 10, 15, 48),
},
{
	id: 5,
	title: 'Call to mom',
	isDone: false,
	category: 3,
	isUrgent: true,
	description: 'Tell about a new student program',
	creationDate: new Date(2022, 0, 10, 12, 15, 45),
},
{
	id: 6,
	title: 'Return the book to Tom',
	isDone: false,
	category: 4,
	isUrgent: true,
	description: 'Twilight',
	creationDate: new Date(2022, 0, 10, 14, 6, 18),
},
{
	id: 7,
	title: 'Feed the cats',
	isDone: false,
	category: 1,
	isUrgent: false,
	description: 'tuesday, thursday, saturday, sunday',
	creationDate: new Date(2022, 0, 13, 15, 3, 45),
},
{
	id: 8,
	title: 'Watch the film',
	isDone: false,
	category: 4,
	isUrgent: false,
	description: 'Nobody',
	creationDate: new Date(2022, 0, 10, 18, 18, 3),
},
];

const categories = [{
	id: 1,
	title: 'home',
},
{
	id: 2,
	title: 'shop',
},
{
	id: 3,
	title: 'family',
},
{
	id: 4,
	title: 'friends',
},
{
	id: 5,
	title: 'health',
},
];

module.exports = { todos, categories };
